### ISSUE TITLE
Change SyncWord (and other LoRa Settings...) Portenta Vision Shield (LoRa)

### ISSUE THREAD

**Issue by baarratia** [hpssjellis/portenta-pro-community-solutions#1]
Hi! Awesome work.

I'm trying to communicate a Raspberry Pi + Dragino LoRa Shield with an Arduino Portenta + Vision Shield. I've already tested your dot342-serial-lora code and it works perfectly in order to send and receive messages using 2 Portentas, but I'm trying to expand the code in order to send messages between different devices. 
It would be nice to know how to change or what are the default LoRa settings of the Portenta (SF, Bandwidth, Coding Rate, Syncword, etc...). 
I have been trying some stuff but still nothing... Do you have any idea how to tackle this?

Thanks!

**Comment by hpssjellis** [comment]
@baarratia  That is a whole can of confusing worms Ben. What I did to make LoRa work on the Portenta is explained here 

https://github.com/arduino-libraries/MKRWAN/issues/87#issuecomment-817012399

but probably all you need is to have a look at the extras folder here

https://github.com/hpssjellis/portenta-pro-community-solutions/tree/main/examples/dot3-portenta-vision-shields/dot34-pure-lora/dot343-extras


all my months of research are here

https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/tree/master/research/LoRaWan/grumpyOldPizza

I am still torn between LoRa and LoRaWan, still not sure what is the best approach. Good luck with your inter board connections.

**Comment by hpssjellis** [comment]
@baarratia  If you want to change the Dragino LoRa Shield to these settings their should not be any issues, if you want to change the settings on the Portenta Murata module then things are difficult. Here are the settings you want: 


```

    LoRaRadio.begin(915000000);
    LoRaRadio.setFrequency(915000000);
    LoRaRadio.setTxPower(1);    //default 14
    LoRaRadio.setBandwidth(LoRaRadio.BW_125);
    LoRaRadio.setSpreadingFactor(LoRaRadio.SF_7);
    LoRaRadio.setCodingRate(LoRaRadio.CR_4_5);
    LoRaRadio.setLnaBoost(true);
```

and herre is the code that they are set  

https://github.com/hpssjellis/portenta-pro-community-solutions/blob/a3c594a22616ca8ab4c7dc266df0b574d1bedd08/examples/dot3-portenta-vision-shields/dot34-pure-lora/dot343-extras/murata-lora-grumpyoldpizza.ino

**Comment by baarratia** [comment]
Thanks! I'll try it and let you know how it goes, maybe it can be useful for other people...

**Comment by baarratia** [comment]
Hi again, I've achieved to send messages in raw LoRa between the Dragino and the Portenta, but only adjusting the settings in the Dragino in order to match the ones you showed me here:

> 
>     LoRaRadio.begin(915000000);
>     LoRaRadio.setFrequency(915000000);
>     LoRaRadio.setTxPower(1);    //default 14
>     LoRaRadio.setBandwidth(LoRaRadio.BW_125);
>     LoRaRadio.setSpreadingFactor(LoRaRadio.SF_7);
>     LoRaRadio.setCodingRate(LoRaRadio.CR_4_5);
>     LoRaRadio.setLnaBoost(true);

I'll be playing with the Portenta a little more, I want to change its settings, but for now it has been tedious and a little frustrating... 
Thanks for your help!

**Comment by hpssjellis** [comment]
@baarratia I probably should make a video about how to do it, since [grumpyOldPizza](https://github.com/GrumpyOldPizza/ArduinoCore-stm32l0) is very frustrating to get setup, but actually kind of fast to work with. How are you doing with it? It is to advanced for me to teach in my class but a video might be useful for people in your situation, just need to find time.

**Comment by baarratia** [comment]
Hi again, a video would be great!
Right now I'm trying to flash the "portenta-murata-bridge" code to my portenta using a Ubuntu Virtual Machine on my Macbook Pro. I followed the instructions and made some assumptions (clone the visual_shield branch...) and the code is compiling, but when Uploading at some point the Portenta is losing connection and the operation fails.

Any advice?

Thanks again :)

**Comment by hpssjellis** [comment]
@baarratia  I am impressed you got a virtual machine working, my WSL (windows subsystem for Linux) days are long over. I may have started too early as it might be fine now.

I will try to get a video out or at least better instructions. Once working it is much faster than running Portenta code. Bit worried about reinstalling it on my Ubuntu machine again as I may screw it up. Will see if I have another Linux machine lying around.

**Comment by hpssjellis** [comment]
@baarratia While trying to make a video, I also could not get the Portenta-muratta-bridge.ino [here](https://github.com/hpssjellis/portenta-pro-community-solutions/tree/main/examples/dot3-portenta-vision-shields/dot34-pure-lora/dot343-extras) working so I have updated the github with working code. Hope that helps.

**Comment by hpssjellis** [comment]
[Here](https://www.youtube.com/watch?v=d2lkL6oCsgg&list=PL57Dnr1H_egtm0pi-okmG0iE_X5dROaLw&index=44) is the video of things working. It is not a video of installation, but hopefully it will help in some way.

**Comment by baarratia** [comment]
Amazing! I'll let you know how it goes as soon as I try it...

Thanks again! 👏
